[env:esp32-c3-devkitm-1]
board           = esp32-c3-devkitm-1
framework       = arduino
platform        = espressif32
monitor_speed   = 115200
lib_extra_dirs  = ../..
build_flags     =
    -std=gnu++11
    -DKAREN_MQTT_DEBUG=1
lib_deps        =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21
